[package]
name = "zdisamar-rust-port"
version = "0.0.1"
edition = "2024"

[lib]
name = "zdisamar"
path = "rust_src/lib.rs"

[[test]]
name = "common_units"
path = "tests/rust/common/units.rs"

[[test]]
name = "common_lut_controls"
path = "tests/rust/common/lut_controls.rs"

[[test]]
name = "input_atmospheric_types"
path = "tests/rust/input/atmospheric_types.rs"

[[test]]
name = "input_scene_primitives"
path = "tests/rust/input/scene_primitives.rs"

[[test]]
name = "input_binding"
path = "tests/rust/input/binding.rs"

[[test]]
name = "input_atmosphere"
path = "tests/rust/input/atmosphere.rs"

[[test]]
name = "input_particles"
path = "tests/rust/input/particles.rs"

[[test]]
name = "input_measurement"
path = "tests/rust/input/measurement.rs"

[[test]]
name = "input_instrument"
path = "tests/rust/input/instrument.rs"

[[test]]
name = "input_observation_model"
path = "tests/rust/input/observation_model.rs"

[[test]]
name = "input_absorber"
path = "tests/rust/input/absorber.rs"

[[test]]
name = "input_reference_data"
path = "tests/rust/input/reference_data.rs"

[[test]]
name = "input_scene"
path = "tests/rust/input/scene.rs"

[[test]]
name = "forward_model_radiative_transfer"
path = "tests/rust/forward_model/radiative_transfer.rs"

[[test]]
name = "forward_model_spectral_math"
path = "tests/rust/forward_model/instrument_grid/spectral_math.rs"

[[test]]
name = "forward_model_implementations"
path = "tests/rust/forward_model/implementations.rs"

[dependencies]
