[package]
name = "zdisamar-rust-port"
version = "0.0.1"
edition = "2024"

[lib]
name = "zdisamar"
path = "rust_src/lib.rs"

[[test]]
name = "common_units"
path = "tests/rust/common/units.rs"

[[test]]
name = "common_lut_controls"
path = "tests/rust/common/lut_controls.rs"

[[test]]
name = "input_atmospheric_types"
path = "tests/rust/input/atmospheric_types.rs"

[[test]]
name = "input_binding"
path = "tests/rust/input/binding.rs"

[[test]]
name = "input_bands"
path = "tests/rust/input/bands.rs"

[[test]]
name = "input_geometry"
path = "tests/rust/input/geometry.rs"

[[test]]
name = "input_measurement"
path = "tests/rust/input/measurement.rs"

[[test]]
name = "input_surface"
path = "tests/rust/input/surface.rs"

[dependencies]
