pub const Error = error{
    CatalogNotBootstrapped,
    InvalidPlan,
    InvalidRequest,
    MissingScene,
    MissingModelFamily,
    MissingTransportRoute,
    MissingObservationInstrument,
    UnsupportedModelFamily,
    PreparedPlanLimitExceeded,
    WorkspacePlanMismatch,
    DerivativeModeMismatch,
    UnsupportedDerivativeMode,
    UnsupportedCapability,
    PluginPrepareFailed,
    PluginExecutionFailed,
};
