pub const MAX_LINE_SHAPE_SAMPLES: usize = 2048;
pub const MAX_LINE_SHAPE_NOMINALS: usize = 256;
pub const MAX_OPERATIONAL_REFSPEC_TEMPERATURE_COEFFICIENTS: usize = 8;
pub const MAX_OPERATIONAL_REFSPEC_PRESSURE_COEFFICIENTS: usize = 12;
